import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <main className="m-20 flex flex-col items-center justify-center gap-12">
      <div className="flex justify-center">
        <Image src="/logo.svg" alt="logo" width={120} height={100} />
      </div>
      <div className="flex flex-col items-center justify-center gap-4">
        <h2 className="text-3xl font-bold text-primary">Fit-Fusion AI</h2>
        <p className="text-md font-semibold text-center">
          A one stop destination for all your fitness needs.
        </p>
      </div>
      <div className="flex flex-col gap-4">
        <p className="text-center">
          Diet Plans, Workout Plans generated by Google's very own
          <br /> Gemini AI are eager to find you.
        </p>
        <Link href={'/dashboard'}>
          <Button className="gap-2 w-full bg-primary text-white">
            Get Started <ArrowRight />
          </Button>
        </Link>
      </div>
      <footer className="text-center">
        Made by <Link href={'https://threed-web-dev-portfolio.onrender.com'}>LVS Sandeep Kumar</Link>
      </footer>
    </main>
  );
}
